server:
  port: 8081

spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://postgres:5432/company_db?currentSchema=company
    username: postgres
    password: qzwxecrv
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true