server:
  port: 8081

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://postgres:5432/company_db?currentSchema=company
    username: postgres
    password: qzwxecrv
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: company-service

management:
  endpoints:
    web:
      exposure:
        include: health