spring:
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/companies/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
