spring.application.name=company-service
spring.datasource.url=jdbc:postgresql://localhost:5432/company_db?currentSchema=public
spring.datasource.username=company_user
spring.datasource.password=11
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true